//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NetrebiakEntities : DbContext
    {
        public NetrebiakEntities()
            : base("name=NetrebiakEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
    
        public virtual int p_insert_Address(string state, string city, string street, string building, Nullable<int> flat)
        {
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var streetParameter = street != null ?
                new ObjectParameter("street", street) :
                new ObjectParameter("street", typeof(string));
    
            var buildingParameter = building != null ?
                new ObjectParameter("building", building) :
                new ObjectParameter("building", typeof(string));
    
            var flatParameter = flat.HasValue ?
                new ObjectParameter("flat", flat) :
                new ObjectParameter("flat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_insert_Address", stateParameter, cityParameter, streetParameter, buildingParameter, flatParameter);
        }
    }
}
